### ISSUE TITLE
import 'package:dart_style/dart_style.dart' takes a lot of time (~8 seconds)

### ISSUE THREAD

**Issue by topperspal** [dart-lang/dart_style#1124]
Even the simplest program takes ~8 seconds. Why it is too slow?
```dart
import 'package:dart_style/dart_style.dart';

void main() {}
```

if I don't import the library, the program exits immediately.

### pubspec.yaml
```yaml
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  basics: ^0.9.0
  code_builder: ^4.1.0
  collection: ^1.16.0
  dart_style: ^2.2.3
  recase: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
```
