### ISSUE TITLE
[Formatting issue] Dart format force add commas

### ISSUE THREAD

**Issue by JeromeGsq** [dart-lang/dart_style#1724]
**What input code did you provide to the formatter?**

```dart
import 'package:flutter/material.dart';

// Widgets
Widget text() {
  return RichText(
    text: const TextSpan(
      children: [
        TextSpan(text: 'a', style: TextStyle(fontWeight: FontWeight.bold)),
        TextSpan(text: 'b', style: TextStyle(fontWeight: FontWeight.bold)),
      ],
    ),
  );
}
```

**What output did the formatter produce?**

```dart
import 'package:flutter/material.dart';

// Widgets
Widget text() {
  return RichText(
    text: const TextSpan(
      children: [
        TextSpan(
          text: 'a',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        TextSpan(
          text: 'b',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
      ],
    ),
  );
}
```

**What output did you expect or want the formatter to produce?**

The formatter add a comma after `FontWeight.bold)`, but I don't want it.

```dart
import 'package:flutter/material.dart';

// Widgets
Widget text() {
  return RichText(
    text: const TextSpan(
      children: [
        TextSpan(text: 'a', style: TextStyle(fontWeight: FontWeight.bold)),
        TextSpan(text: 'b', style: TextStyle(fontWeight: FontWeight.bold)),
      ],
    ),
  );
}
```

**Anything else we should know?**
I use Cursor.

``` 
// versions
✗ flutter --version
Flutter 3.32.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision be698c48a6 (4 days ago) • 2025-05-19 12:59:14 -0700
Engine • revision 1881800949 (4 days ago) • 2025-05-19 10:54:07 -0700
Tools • Dart 3.8.0 • DevTools 2.45.1
```

``` 
// .vscode/settings
{
  "dart.lineLength": 512,
}
```

``` 
// analysis_options.yaml
formatter:
  trailing_commas: preserve
  page_width: 512
analyzer:
  errors:
    dead_code: warning
    missing_required_param: error
    missing_return: error
    todo: warning
    invalid_annotation_target: ignore
    prefer_foreach: ignore
  plugins:
    - package: custom_lint
linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - always_declare_return_types
    - always_put_control_body_on_new_line
    # - always_put_required_named_parameters_first # we prefer having parameters in the same order as fields https://github.com/flutter/flutter/issues/10219
    # - always_specify_types
    - annotate_overrides
    - avoid_annotating_with_dynamic # conflicts with always_specify_types
    # - avoid_as
    # - avoid_bool_literals_in_conditional_expressions # not yet tested
    # - avoid_catches_without_on_clauses # we do this commonly
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    # - avoid_double_and_int_checks # only useful when targeting JS runtime
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    # - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types # not yet tested
    - avoid_init_to_null
    # - avoid_js_rounded_ints # only useful when targeting JS runtime
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters # not yet tested
    # - avoid_private_typedef_functions # we prefer having typedef (discussion in https://github.com/flutter/flutter/pull/16356)
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    # - avoid_returning_null # there are plenty of valid reasons to return null
    - avoid_returning_this
    # - avoid_setters_without_getters # not yet tested
    - avoid_shadowing_type_parameters # not yet tested
    - avoid_single_cascade_in_expression_statements # not yet tested
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    # - avoid_types_on_closure_parameters # conflicts with always_specify_types
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_print
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    # - cascade_invocations # not yet tested
    # - close_sinks # not reliable enough
    # - comment_references # blocked on https://github.com/flutter/flutter/issues/20765
    - constant_identifier_names # needs an opt-out https://github.com/dart-lang/linter/issues/204
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures # not yet tested
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names # not yet tested
    # - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    # - invariant_booleans # too many false positives: https://github.com/dart-lang/linter/issues/811
    # - join_return_with_assignment # not yet tested
    - library_names
    - library_prefixes
    # - lines_longer_than_80_chars # not yet tested
    # - literal_only_boolean_expressions # too many false positives: https://github.com/dart-lang/sdk/issues/34181
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures # not yet tested
    # - omit_local_variable_types
    # - one_member_abstracts # too many false positives
    # - only_throw_errors # https://github.com/flutter/flutter/issues/5792
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    # - parameter_assignments # we do this commonly
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    # - prefer_constructors_over_static_methods # not yet tested
    - prefer_contains
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies # conflicts with https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#consider-using--for-short-functions-and-methods
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables # not yet tested
    - prefer_generic_function_type_aliases
    - prefer_initializing_formals
    - prefer_int_literals # not yet tested
    - prefer_interpolation_to_compose_strings # not yet tested
    - prefer_is_empty
    # - prefer_is_not_empty # disable until NNBD, see https://github.com/flutter/flutter/pull/32711#issuecomment-492930932
    - prefer_iterable_whereType
    # - prefer_mixin # https://github.com/dart-lang/language/issues/32
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    # - public_member_api_docs # enabled on a case-by-case basis; see e.g. packages/analysis_options.yaml
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    # - unawaited_futures # too many false positives
    - unnecessary_await_in_return # not yet tested
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    # - unnecessary_lambdas # has false positives: https://github.com/dart-lang/linter/issues/498
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    # - use_function_type_syntax_for_parameters # not yet tested
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    # - use_setters_to_change_properties # not yet tested
    # - use_string_buffers # has false positives: https://github.com/dart-lang/sdk/issues/34182
    # - use_to_and_as_if_applicable # has false positives, so we prefer to catch this by code-review
    - valid_regexps
    - void_checks # not yet tested

```

Thanks!
