### ISSUE TITLE
Dartfmt pins to package dependency on travis: it shouldn't.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#643]
I'm running into a number of projects on Travis where I see the following failure:

```
$ dart --version
Dart VM version: 1.24.2 (Thu Jun 22 08:43:26 2017) on "linux_x64"

$ unformatted=`dartfmt -n .`
Files are unformatted:
test/span_for_element_test.dart
```

[Example failure](https://travis-ci.org/dart-lang/source_gen/jobs/251776420) and `.travis.yml`:

```yaml
language: dart
sudo: false
dart:
  - dev
  - stable
  - 1.22.1
dart_task:
  # Run the tests -- include the default-skipped presubmit tests
  - test: --platform vm --run-skipped
  - dartfmt
  - dartanalyzer
matrix:
  exclude:
    - dart: 1.22.1
      dart_task: dartfmt
    - dart: 1.22.1
      dart_task: dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
```

But running `dartfmt -n .` locally reports nothing, so I can't fix the problem automatically.

I've uploaded a specific file [`span_for_element_test.dart`](https://gist.github.com/matanlurey/c41060942425c2b30a877e1c1a3a7e2f) which runs into this problem.

Here is my local development environment:

```
dart --version
Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
```

I've started to see these failures only recently. In both cases I was able to manually fixing the problem by moving around long-string literals. For example, this seems (?) to fail:

```dart
  setUpAll(() async {
    final resolver = await resolveSource(
        r'''
      library test_lib;
      
      abstract class Example implements List {}
    ''',
        inputId: new AssetId('test_lib', 'lib/test_lib.dart'));
    library = resolver.getLibraryByName('test_lib');
  });
```

But this does not:

```dart
  setUpAll(() async {
    final resolver = await resolveSource(
      r'''
      library test_lib;
      
      abstract class Example implements List {}
    ''',
      inputId: new AssetId('test_lib', 'lib/test_lib.dart'),
    );
    library = resolver.getLibraryByName('test_lib');
  });
```

[Here is an example][example] of that same travis run succeeding after this change.

[example]: https://travis-ci.org/dart-lang/source_gen/builds/251782642

/cc @nex3 (for travis) and @kevmoo (for FYI).
